lib/passport-azure-ad/samlstrategy.js
lib/passport-azure-ad/wsfedstrategy.js

Support passReqToCallback option

---

README.md

All samples in this project need updating. I started with `README.md`. The samples in the folders should follow suite.

Update sample in README.md

---

lib/passport-azure-ad/metadata.js
lib/passport-azure-ad/saml.js
lib/passport-azure-ad/wsfedsaml.js
package.json

Fixed issue #36 (regression)
Fixed issue #22 (regression)
Fixed issue #14

Fixed multiple issues that were previously fixed but not in convergence branch.

---

examples/login-oidc/app.js
examples/login-saml/app.js
examples/login-wsfed/app.js
lib/passport-azure-ad/saml.js
package.json

Updated cookie parser as @joaomoreno suggested in #28. Thanks!
Updated for regression of utf8 issue in #24

Updated cookie parser as @joaomoreno suggested in #28. Thanks!

---

lib/passport-azure-ad/oidcstrategy.js

1. Typo in setting an option
2. Metadata should be defined before use

oidcstrategy fixes

---

lib/passport-azure-ad/oidcsetup.js

Looks like a minor issue with logging, `clientID` should come from the `config` object here.

OIDCSetup.js: clientID needs to come from the config.

---

lib/passport-azure-ad/metadata.js
lib/passport-azure-ad/oidcsetup.js
lib/passport-azure-ad/oidcstrategy.js
lib/passport-azure-ad/tokenValidator.js

Having been staring at Bunyan logs for a while, I figured I would fix a few typos in the log output...
Note that I haven't installed the dev dependencies on this box yet so have not run the tests (sloppy, I know!), so if tests are validating the error messages or log output and expect the misspellings, then they will fail. I'll try and run the tests when I get a chance.
Thanks!

Making some log spelling changes.

---

lib/passport-azure-ad/oidcstrategy.js

I see the following issue when trying to authenticate:
```
"Cannot read property 'code' of undefined"
```
This resolves that issue.

adding check for req.body existence

---

examples/login-oidc/README.md

The display looks weird, corrected the format of the README file

Corrected the format of oidc README

---

lib/bearerstrategy.js

Added more comments on the options and usage of bearer strategy

Added more comments to bearstrategy.js

---

lib/bearerstrategy.js
package.json
test/bearer_pem_mochaTest.js
test/bearer_simple_mochaTest.js

Metadata loading is async, passport may use the metadata content even if the metadata loading is not finished, for instance, keys. In this fix, the following are done:
(1) load metadata dynamically at `authenticate` time, from server or memory cache
(2) solved async issue using waterfall
(3) added a couple of unit tests

Solved #90: Cannot read property 'keys' of undefined

---

Gruntfile.js
README.md
contributing.md
package.json
test/Chai-passport_test/bearer_pem_test.js
test/Chai-passport_test/bearer_simple_test.js
test/Nodeunit_test/metadata_test.js
test/Nodeunit_test/oidc_b2c_test.js
test/Nodeunit_test/oidc_test.js
test/Nodeunit_test/oidc_v2_test.js
test/Nodeunit_test/pem_test.js
test/Nodeunit_test/saml_test.js
test/Nodeunit_test/validator_test.js
test/Nodeunit_test/wsfed_test.js

1. separated tests using nodeunit tool and chai-passport-strategy tool
2. added readme on the structure of test folder and instructions on running test

Testing reorganization

---

README.md

Adding Versions section with current, minimum  recommended versions, link  to ChangeLog

adding Versions section to readme

---

README.md

adding Versions section to readme

adding Versions section to readme (#190)

---

Changelog.md
README.md

(1) added changelog content of 2.x
(2) updated minimum recommended version

udpate readme and changelog

---

CHANGELOG.md
README.md
lib/bearerstrategy.js

(1) added changes in 1.x to changelog of 2.x
(2) update the minimum recommended version

update changelog and readme

---

lib/aadutils.js
package.json

Update telemetry to use package name and version

---

CHANGELOG.md
README.md
lib/constants.js
lib/jsonWebToken.js
lib/oidcstrategy.js
package.json
test/Chai-passport_test/constants_test.js
test/Chai-passport_test/oidc_dynamic_tenant_test.js
test/Nodeunit_test/oidc_test.js

(1) Issue #229, use tenant id dynamically for each request
(2) Issue #233, provide documentation with more details
(3) Issue #123, Question: what is the difference between OIDCStrategy and BearerStrategy. Which one should I use?
(4) now pass all the errors to async.waterfall and call self.fail at one place instead of everywhere
(5) updated readme and changelog

Couple of issues

---

CHANGELOG.md
lib/jsonWebToken.js

(1) updated changelog with the list of fixed bugs
(2) allow 1 more second for the nbf validation

update changelog and add fix to nbf validation

---

README.md
lib/bearerstrategy.js
lib/jsonWebToken.js
lib/oidcstrategy.js
test/Chai-passport_test/b2c_oidc_hybrid_and_code_flow_test.js
test/Chai-passport_test/b2c_oidc_implicit_flow_test.js
test/Chai-passport_test/clock_skew_test.js
test/Chai-passport_test/oidc_common_endpoint_test.js
test/Chai-passport_test/oidc_hybrid_and_code_flow_test.js
test/Chai-passport_test/oidc_implicit_flow_test.js

Issue #245 Make clock skew configurable

---

lib/index.js
lib/oidcstrategy.js

Enhancement for issue https://github.com/AzureAD/passport-azure-ad/issues/261

Adding prompt,login_hint,domain_hint

---

CHANGELOG.md
README.md
lib/jwe.js
lib/oidcstrategy.js
package.json
test/Chai-passport_test/jwe_test.js
test/End_to_end_test/app/app.js
test/End_to_end_test/app/app_for_jwe.js
test/End_to_end_test/oidc_jwe_test.js

added support of id_token in JWE compact serialization format. Supported key encryption algorithms (alg) are: RSA1_5, RSA-OAEP, A128KW, A256KW, dir; supported content encryption algorithms (enc) are: A128CBC-HS256, A192CBC-HS384, A256CBC-HS512, A128GCM, and A256GCM.

JWE support

---

lib/bearerstrategy.js

switch to dev

---

README.md

See commit - corrects minor grammatical issue.

Corrects minor grammatical issue with an/a

---

.travis.yml
CHANGELOG.md
README.md
lib/aadutils.js
package.json

Updated version for base64Url

---

lib/cookieContentHandler.js
lib/oidcstrategy.js

See description here: https://github.com/AzureAD/passport-azure-ad/issues/399

Make state cookie domain configurable

---

lib/oidcstrategy.js

Fix for the policyChecker that will never work as the pathname will never contain query parameters.

Fixed policyChecker bug

---

README.md
lib/metadata.js
lib/oidcstrategy.js
package.json

I wrote this a long time ago to authenticate behind a corporate proxy. Since I periodically get pinged in my issue #341 that other people need this I am creating this PR.
I have not used this in years and I do not work in the Microsoft tech stack any more, so maybe there is a better way to do it.

#341 add in basic proxy agent

---

lib/bearerstrategy.js

https://github.com/AzureAD/passport-azure-ad/issues/375

Fix for 357, malformed json bug
