LICENSE, README.md, examples/login-oidc/README.md, examples/login-oidc/app.js, examples/login-oidc/client_config.js, lib/passport-azure-ad/oidcstrategy.js
* Support for v1 or v2 of our API. You just change the knobs and the metadata endpoint!
* Massive update that fixes a lot that was wrong with the original OpenID Connect Implementation.
* Lots of new knobs given to you that you can pass in. Look at the client_config.js example to see these. In detail:
* You can now specify if user profile should be loaded. (HINT: You shouldn't - as we don't have a user profile lookup.) Default is to skip which you should for AzureAD and MSA. #51
* Turns out that my OpenID Connect implementation only have OAuth2 query support, and passed code and tokens through such. This is against spec, against nature, and now fixed. #50
* Both the id_token code and id_token flows now support POST and will do the right thing no matter if using v1 or v2. Fragment still …
=> OpenID Connect POST fix, Support for v1 or v2 of our API, more.

examples/login-oidc-b2c/README.md, examples/login-oidc-b2c/app.js, examples/login-oidc-b2c/client_config_b2c.js, examples/login-oidc-b2c/package.json, examples/login-oidc-b2c/routes/index.js, examples/login-oidc-b2c/routes/user.js, examples/login-oidc-b2c/views/account.ejs, examples/login-oidc-b2c/views/index.ejs, examples/login-oidc-b2c/views/layout.ejs, examples/login-oidc/client_config_v1.js, lib/passport-azure-ad/oidcstrategy.js, package.json
Another big fancy update!
* B2C Support - when it launches you can easily use policies in your node.js application! Just check out /examples/login-oidc-b2c for details. 
* You just specify the tenantName: and then add some routes.
Biggest speed improvement: I've implemented caching of the metadata with cache-manager.
* This increases speed amazingly.
* I needed to do this because now we load metadata at clicktime and not at server launch, so this was required.
* I set the cache expiry to 30 mintues for now, we'll see how that goes. May expose it out in config if users want.
=> B2C Support and more!

lib/passport-azure-ad/oidcstrategy.js, lib/passport-azure-ad/validator.js, test/oidc_test.js
Several tests in the `oidc-tests.js` file were not actually exercising the product as they throw a ReferenceError, which was caught by the test.
This PR includes two fixes:
1. Fix `oidc-tests.js` tests to actually test the product under test.
2. Fix duplicate tokenURL validator configuration entry.
a. The isURL validator indirectly checks for non-empty strings which was the other configured validator.
=> Fix strategy tests

examples/login-oidc-b2c/app.js, examples/login-oidc-b2c/client_config_b2c.js, examples/login-oidc/app.js, examples/login-oidc/client_config_v1.js, examples/login-oidc/client_config_v2.js, examples/server-oauth2-b2c/server.js, examples/server-oauth2-b2c/server_config.js, examples/server-oauth2/server.js, examples/server-oauth2/server_config.js, lib/passport-azure-ad/bearerstrategy.js, lib/passport-azure-ad/logging.js, lib/passport-azure-ad/metadata.js, lib/passport-azure-ad/oidcsetup.js, lib/passport-azure-ad/oidcstrategy.js, lib/passport-azure-ad/saml.js, lib/passport-azure-ad/tokenValidator.js, lib/passport-azure-ad/wsfedstrategy.js, package.json, test/metadata_test.js
Logging is now much quieter and allows for future plugging in of other logger if required.
Details:
* The logging now defaults to an ERROR level logging to stderr no matter what
* The logging now defaults to WARN level logging for everything else, but this can be overridden by a setting passed in to the Strategy if desired
* This is only for ODIC and Bearer as WS-Fed and SAML are out of support (but anyone is welcome to add it in, should be minimal)
=> Fixed logging, ReqToCallaback, and passing state.

lib/passport-azure-ad/saml.js, lib/passport-azure-ad/samlutils.js
I found the same behavior as issue (https://github.com/AzureAD/passport-azure-ad/issues/70).
That being said I made the change and submitted a pull-request.
Kudos to @fredrikj
=> Adjusted null `this.certs` in checkSignature

lib/passport-azure-ad/oidcstrategy.js
scopeSeparator is used later in the `authenticate` method of this strategy. Looks like there was some code copied from `passport-oauth2` while this strategy inherits from `passport-strategy` instead.
Without a default, auth requests fail when providing additional scopes as Array. Even if a `scopeSeparator` option was provided, it wasn't respected anyway
=> add scopeSeparator option

lib/passport-azure-ad/oidcstrategy.js
Hey
I've noticed that although I've set the state parameter it was not sent to azure ad in authorize request. I've fixed the bug.
Thanks,
Omer
=> fix - read state from options if it is set

lib/aadutils.js
Whitespace is being added to the pem cert as a result of how the ES6 template string is written on multiple lines in rsaPublicKeyPem() in aadutils.js. fixes #117. this causes the buffer.js and/or crypto library verify function to fail with `TypeError: Invalid hex string` until `encodedPubkey` is converted and then failing with `Error: PEM_read_bio_PUBKEY failed` until `pem` is fixed.
=> fix whitespacing issue in rsaPublicKeyPem in aadutils.js fixes #117

lib/bearerstrategy.js
Since opts is initialized at the top of the function to either an empty object or the options variable and the code afterwards assumes it will be an object and modifies its properties we can remove the need to extend the opts into an empty object in the BearerStrategy.call and just combine opts with passReqToCallback
util._extend does not accept more than 2 arguments so currently passReqToCallback is dropped and not forced true unless you set it in your config of your own app
see: https://github.com/defunctzombie/node-util/blob/master/util.js#L572
=> fix BearerStrategy.call _extend leaving out req. fixes #112

lib/pem.js
If there is a match, str.match(regex) always returns at least one group, where
the first group is always the entire match, and the rest are the capturing groups.
Therefore getFirstCapturingGroup returns an array of two groups, and the second
one is the content captured.
Also added some comments on top of pem.js.
=> Solved issue 121: regex error in pem.js

lib/aadutils.js, lib/metadata.js, test/metadata_test.js
"!keys.kid===kid" is "(!keys.kid) === kid", which condition always yields false. Therefore this bug causes us to always use the first key even the kid doesn't match, and that leads to token validation error. It should be "keys.kid !== kid".
The rsaPublicKeyPem in aadutils.js of dev branch also has problem, the `encodedPubKey` has some extra '\n' inside which yield wrong pem.
Unit tests are added.
=> key id check condition fixed

lib/aadutils.js, test/Nodeunit_test/metadata_test.js, test/Nodeunit_test/validator_test.js, typings/browser/ambient/express-serve-static-core/index.d.ts, typings/browser/ambient/node/index.d.ts, typings/main/ambient/express-serve-static-core/index.d.ts, typings/main/ambient/node/index.d.ts
Jenkins policheck script doesn't like the word 'foo', we are replacing 'foo' with the word 'something' so the policheck can pass.
=> work for Jenkins policheck

lib/oidcstrategy.js, test/Chai-passport_test/oidc_error_test.js
When there is 'error' in the response, passport should call this.fail instead of this.error. The difference is:
(1) this.error is for server error
(2) this.fail is for authentication error, where the server has no problem. In this case, the server can redirect the user to login page (or whatever page the developer sets) for authentication.
=> Issue #91, TypeError: this.fail is not a function

Gruntfile.js
Folder name should be `Chai-passport_test` instead of `chai-passport_test`. Tests in this folder run locally, but not on travis, seems my version of npm doesn't distinguish the lower/upper case.
=> Typo in Gruntfile.js

lib/metadata.js, lib/tokenValidator.js
When we have key.n or key.e, we turn it into base64 encoded buffer
```
var modulus64 = new Buffer(key.n, 'base64');
```
Later we feed it to rsaPublicKeyPem function, which does:
```
var modulus =  new Buffer(modulus64, 'base64');
```
Here modulus and modulus64 are the same. Since Buffer(buffer) only takes 1 parameter, 'base64' will be ignored, and this function just makes a copy of modulus. Therefore, we just need to feed key.n or key.e to rasPublicKeyPem instead of turning it into buffer first.
=> Issue #146, duplicate use of "new Buffer"

package.json
">= ~4.0.1" is illegal use, a comparator is composed of an operator and a version (see https://github.com/npm/node-semver and the range grammar). My testing shows ">= ~4.0.1" has the same effect as "~4.0.1", which means only v4.0.x is wanted. This is in fact the issue Jeff Wilconx mentioned in his email, where he was using v4.4.7 and got a warning. The correct one should be ">= 4.0.1".
=> package json mistake

CHANGELOG.md, lib/oidcstrategy.js, test/Chai-passport_test/oidc_hybrid_and_code_flow_test.js, test/Chai-passport_test/oidc_implicit_flow_test.js, test/Chai-passport_test/oidc_incoming_request_test.js
This function assumes options.skipUserProfile can be a function, this is impossible since options.skipUserProfile is read from the config file, it can only be true or false. So let's remove this dead code.
For any code like:
```
self._shouldLoadUserProfile(iss, sub, (err, load) => {
if (err)
err_handling_logic;
callback_function_body;
}
);
```
We don't need _shouldLoadUserProfile to decide if we want to load user profile, so remove the _shouldLoadUserProfile and transform it to
```
// we don't load userinfo unless user set skipUserProfile to false
const load = (self._options.skipUserProfile === false);
callback_function_body;
```
=> remove _shouldLoadUserProfile

lib/saml.js
We spot a bug in `passport-azure-ad` 2 (it affects all versions from 2.0.0 to 2.0.3).
In 0ac89df8679e9e0a2744ccc0de81a620f914a1b8, the `validateSignature` function has been rewritten and a typo on the namespace URI was made: `http://www.w3.org/2000/09/xmldsig#` became `http: //www.w3.org/2000/09/xmldsig#` (notice the extra whitespace added after `http:`).
This change broke the `validateSignature` function. The line `sig.loadSignature(signature.toString());` would always yield a `Cannot read property 'toString' of undefined` message.
=> Fix xpath expression in validateSignature

CHANGELOG.md, lib/aadutils.js, lib/jsonWebToken.js, lib/oidcstrategy.js, lib/validator.js, test/Chai-passport_test/b2c_oidc_implicit_flow_test.js, test/Chai-passport_test/b2c_oidc_incoming_request_test.js, test/Chai-passport_test/oidc_common_endpoint_test.js, test/Chai-passport_test/oidc_hybrid_and_code_flow_test.js, test/Chai-passport_test/oidc_implicit_flow_test.js, test/Chai-passport_test/oidc_incoming_request_test.js, test/Nodeunit_test/oidc_b2c_test.js, test/Nodeunit_test/oidc_test.js, test/Nodeunit_test/oidc_v2_test.js
(1) Rewrote the metadata loading and the configuration code. Restructured OIDCStrategy.
(2) #188 B2C mocha tests (partially done, waiting for the AAD fix of missing nonce to add test for hybrid/code flow)
(3) #165 rename 'callbackURL' and 'returnURL' to 'redirectUrl'.
(4) #189 Extensibility to allow issuer validation when going against commend end point
(5) #194 error message for 'sub' mismatch is incorrect after redeeming 'code'
(6) #218 missing email claim for B2C
=> Fix OIDC B2C problems

lib/jsonWebToken.js
AAD rounds the current time up to the nearest integer for the nbf value, but we round the current time down when we validate the nbf value. This fails the authentication because we thought the current time is before nbf and the token is not active yet.
=> Issue #239 Problems with signin in the updated sample

CHANGELOG.md, README.md, lib/constants.js, lib/jsonWebToken.js, lib/metadata.js, lib/oidcstrategy.js, package.json, test/Chai-passport_test/b2c_oidc_hybrid_and_code_flow_test.js, test/Chai-passport_test/b2c_oidc_implicit_flow_test.js, test/Chai-passport_test/b2c_oidc_incoming_request_test.js, test/Chai-passport_test/oidc_hybrid_and_code_flow_test.js
(1) updated version to 3.0.2 in package.json
(2) removed oniyi-object-transform dependency
(3) set clock skew to 5 minutes as Wilson does. Will make this configurable in the future.
=> fix for 3.0.2

CHANGELOG.md, README.md, package.json
v3.0.2 npm package has this issue. We update the version and re-publish the package.
v3.0.2 npm package contains an End_to_end_test folder, but master branch doesn't have it.
This is due to a git bug. End_to_end_test folder is in sijliu/MQ branch, if I open
passport-azure-ad in sublime, modify some files in End_to_end_test, then do a
"git reset --hard" and switch back to the master branch, then the End_to_end_test folder
will show up in the local master branch. This git behavior is incorrect, that folder
should not show up.
Even though that folder shows up, if I do a 'git status', it says the local master is the
same as the remote master branch, so git doesn't recognize it. However when I do a npm
publish, npm considers the End_to_end_test folder part of the master branch, and this
causes …
=> Issue #248 End_to_end_test showing up in test folder

lib/bearerstrategy.js, test/Chai-passport_test/bearer_flow_test.js
Fixes Issue #254 - passReqToCallback does not work with bearer strategy
When 'passReqToCallback' is set to true, the callback passed in to a new strategy should get called with the three param option (req, user, done). It does not. Instead the two param option is always called (user, done).
In the bearerstrategy jwtVerify function, self.passReqToCallback was being used instead of self._options.passReqToCallback. This cause the callback passed in to a new strategy to get called with the two param option even when "passReqToCallback" is set to true.
=> Using bearer strategy passReqToCallback = true does not work

lib/oidcstrategy.js, test/Chai-passport_test/b2c_oidc_hybrid_and_code_flow_test.js
We used to only allow 'Bearer' for token_type, now we make it case insensitive and allow something like 'bearer'.
=> Issue #264 make token_type case insensitive for OIDCStrategy

README.md, lib/oidcstrategy.js, test/Chai-passport_test/b2c_oidc_hybrid_and_code_flow_test.js, test/Chai-passport_test/b2c_oidc_implicit_flow_test.js, test/End_to_end_test/oidc_b2c_test.js
When we create a B2C policy, the policy is used to be stored in 'acr' claim in id_token. Now this is configurable, and policy is stored in 'tfp' instead by default.
=> Issue #256 Support 'tfp' for B2C

test/Chai-passport_test/b2c_oidc_hybrid_and_code_flow_test.js, test/Chai-passport_test/b2c_oidc_implicit_flow_test.js, test/Chai-passport_test/b2c_oidc_incoming_request_test.js, test/Chai-passport_test/bearer_flow_test.js, test/Chai-passport_test/bearer_token_in_req_test.js, test/Chai-passport_test/clock_skew_test.js, test/Chai-passport_test/constants_test.js, test/Chai-passport_test/oidc_common_endpoint_test.js, test/Chai-passport_test/oidc_dynamic_tenant_test.js, test/Chai-passport_test/oidc_hybrid_and_code_flow_test.js, test/Chai-passport_test/oidc_implicit_flow_test.js, test/Chai-passport_test/oidc_incoming_request_test.js, test/Chai-passport_test/sessionContentHandler_test.js, test/End_to_end_test/bearer_b2c_test.js, test/End_to_end_test/bearer_test.js, test/End_to_end_test/oidc_b2c_test.js, test/End_to_end_test/oidc_v1_test.js, test/End_to_end_test/oidc_v2_test.js
(1) allow more time by setting a timeout for tests in Chai-passport_test
(2) allow more time for the signin key to show up in End_to_end_test. Remove the unnecessary click of the 'continue' button in b2c updateprofile page and the 'cancel' button in b2c signup page.
=> Fix Jenkins failure

README.md, lib/cookieContentHandler.js, lib/jwe.js, lib/oidcstrategy.js, test/Chai-passport_test/cookie_test.js, test/End_to_end_test/app/app_for_cookie.js, test/End_to_end_test/oidc_cookie_test.js
We used to save state and nonce in session, so session is always required. Now we can encrypt and decrypt
state and nonce, and put them into cookie, so session is no longer mandatory.
We provided two more options: useCookieInsteadOfSession, cookieEncryptionKeys. To use cookie, first set the first option to true.
For the second option, provide an array of { key: '...', iv: '...' } items. For each item, key is any string
of size 32, and iv is any string of size 12. We will use the first item (with AES-256-GCM algorithm) to encrypt cookie, but we try every
item to decrypt cookie, so you can easily do key rollover.
=> Issue #285 express-session free support

lib/oidcstrategy.js
generateOidcPEM throws an error if kid is missing, so we have to use try catch here.
=> catch exception thrown for missing kid

lib/oidcstrategy.js
When trying to use this strategy, I ran into a lot of trouble using the cookies.
All of my calls resulted with the following error, crashing my server:
```
TypeError: Cannot read property 'cookie' of undefined
CookieContentHandler.add (node_modules/passport-azure-ad/lib/cookieContentHandler.js:130:6)
Strategy.flowInitializationHandler [as _flowInitializationHandler] (node_modules/passport-azure-ad/lib/oidcstrategy.js:1339:32)
async.waterfall (node_modules/passport-azure-ad/lib/oidcstrategy.js:630:23)
fn (node_modules/passport-azure-ad/node_modules/async/lib/async.js:746:34)
node_modules/passport-azure-ad/node_modules/async/lib/async.js:1213:16
node_modules/passport-azure-ad/node_modules/async/lib/async.js:166:37
node_modules/passport-azure-ad/node_modules/async/lib/async.js:706:43 …
```
=> Fix: Cannot set cookie on the response.

lib/oidcstrategy.js
1. get access token using client assertion issue fixed
2. It will also close this issue => https://github.com/AzureAD/passport-azure-ad/issues/388
=> get access token using client assertion issue fixed

lib/oidcstrategy.js
Hi,
Had an issue with policy validation, turns out it is a part of path now:
https://login.microsoftonline.com/te/UUID/b2c_1_elk/oauth2/authorize
=> B2C policy is a part of the path as opposed to query param

.travis.yml, package.json
`node@8` is still a few months in LTS.
https://nodejs.org/en/about/releases
=> Update supported Node versions

lib/aadutils.js, lib/cookieContentHandler.js, lib/oidcstrategy.js, test/Chai-passport_test/cookie_test.js
To avoid breaking consumers who are using an http framework where this is not supported, I have added an opt in `cookieSameSite` option to OIDC config.
This will be a minor release.
=> add support for samesite in passport js

.npmignore
Does not seem like any of those are needed to be distributed? :)
I was also wondering about adding *.md here, as nobody reads them from unpacked package, but rather on the npm or github site...
=> Limit number of packaged files

lib/bearerstrategy.js
Fixes an issue where the log output contains `[Object object]` instead of the options to validate object.
=> stringify optionsToValidate when logging
